name: Prueba_GHA
on:
  push:
    paths:
      - '/home/aranzaibarra/GitHubActions/tareas/Ibarra_Ara'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t nombre_imagen .
    
    - name: Run Docker Container
      run: |
        docker run nombre_imagen

