name: Prueba_Token_Secrets

on:
  pull_request:
  push:
    paths:
      - 'tareas/Ibarra_Ara/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker Image
      run: |
        docker build -t aranzaibarra/gitact_hw: tareas/Ibarra_Ara
    - name: Log into Docker Hub
      run: docker login -u aranzaibarra -p ${{ secrets.GITACT_HW_KEY }}
    - name: Push Docker Image to Docker Hub
      run: docker push aranzaibarra/gitact_hw
