name: Prueba_GHA

on:
  pull_request:
  push:
    paths:
      - 'GitHubActions/tareas/Ibarra_Ara/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker Image
      run: |
        docker build -t gitact_hw GitHubActions/tareas/Ibarra_Ara/
    - name: Run Docker Container
      run: |
        docker run gitact_hw

